name: publish to nuget
on:
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: dotnet pack
        shell: powershell
        run: dotnet pack --configuration Release

      - name: dotnet nuget push
        shell: powershell
        run: Get-ChildItem -r *.nupkg | ForEach-Object { $name = $_.FullName; "Pushing $name"; dotnet nuget push $name --api-key '${{ secrets.NUGET_PUSH }}' --source "https://api.nuget.org/v3/index.json" }
